package sky.pojo;

/**
 * Created by Stelawliet on 18/3/25.
 */
public class EmpEx extends Emp {
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbggenerated
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.loc
     *
     * @mbggenerated
     */
    private String loc;

    @Override
    public Integer getDeptno() {
        return deptno;
    }

    @Override
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    public String getLoc() {
        return loc;
    }

    public void setLoc(String loc) {
        this.loc = loc;
    }
}
