package sky.pojo;

public class Salgrade {

    @Override
    public String toString() {
        return "Salgrade{" +
                "grade=" + grade +
                ", losal=" + losal +
                ", hisal=" + hisal +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.grade
     *
     * @mbggenerated
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.losal
     *
     * @mbggenerated
     */
    private Integer losal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.hisal
     *
     * @mbggenerated
     */
    private Integer hisal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.grade
     *
     * @return the value of salgrade.grade
     *
     * @mbggenerated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.grade
     *
     * @param grade the value for salgrade.grade
     *
     * @mbggenerated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.losal
     *
     * @return the value of salgrade.losal
     *
     * @mbggenerated
     */
    public Integer getLosal() {
        return losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.losal
     *
     * @param losal the value for salgrade.losal
     *
     * @mbggenerated
     */
    public void setLosal(Integer losal) {
        this.losal = losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.hisal
     *
     * @return the value of salgrade.hisal
     *
     * @mbggenerated
     */
    public Integer getHisal() {
        return hisal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.hisal
     *
     * @param hisal the value for salgrade.hisal
     *
     * @mbggenerated
     */
    public void setHisal(Integer hisal) {
        this.hisal = hisal;
    }
}