package sky.pojo;

public class Stu {

    @Override
    public String toString() {
        return "Stu{" +
                "sid=" + sid +
                ", sname='" + sname + '\'' +
                ", age=" + age +
                ", gander='" + gander + '\'' +
                ", province='" + province + '\'' +
                ", tuition=" + tuition +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sid
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.sname
     *
     * @mbggenerated
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.gander
     *
     * @mbggenerated
     */
    private String gander;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.tuition
     *
     * @mbggenerated
     */
    private Integer tuition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sid
     *
     * @return the value of stu.sid
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sid
     *
     * @param sid the value for stu.sid
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.sname
     *
     * @return the value of stu.sname
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.sname
     *
     * @param sname the value for stu.sname
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.age
     *
     * @return the value of stu.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.age
     *
     * @param age the value for stu.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.gander
     *
     * @return the value of stu.gander
     *
     * @mbggenerated
     */
    public String getGander() {
        return gander;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.gander
     *
     * @param gander the value for stu.gander
     *
     * @mbggenerated
     */
    public void setGander(String gander) {
        this.gander = gander == null ? null : gander.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.province
     *
     * @return the value of stu.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.province
     *
     * @param province the value for stu.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.tuition
     *
     * @return the value of stu.tuition
     *
     * @mbggenerated
     */
    public Integer getTuition() {
        return tuition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.tuition
     *
     * @param tuition the value for stu.tuition
     *
     * @mbggenerated
     */
    public void setTuition(Integer tuition) {
        this.tuition = tuition;
    }
}