package sky.mapper;

import java.util.List;
import sky.pojo.Salgrade;

public interface SalgradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salgrade
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer grade);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salgrade
     *
     * @mbggenerated
     */
    int insert(Salgrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salgrade
     *
     * @mbggenerated
     */
    Salgrade selectByPrimaryKey(Integer grade);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salgrade
     *
     * @mbggenerated
     */
    List<Salgrade> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salgrade
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Salgrade record);
}